#!/usr/bin/env python

from datetime import datetime
import time
import os
from gi.repository import AppIndicator3 as ap
from gi.repository import Gtk as gtk
from gi.repository import Notify as notify
import sys


